version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - ci_network

  webserver:
    image: nginx:alpine
    container_name: codeigniter_webserver
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - ci_network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci_network

networks:
  ci_network:

volumes:
  db_data:
